### ISSUE TITLE
Missing `@context` serialize

### ISSUE THREAD

**Issue by jschne1der** [International-Data-Spaces-Association/Java-Representation-of-IDS-Information-Model#12] opened 2021-10-01 14:41 UTC
We are witnessing some strange behavior when using `SERIALIZER.serialize(Message header)`. When sending multiple ContractOfferMessages between two Connectors, some fail to send (or are rejected by the receiver) 

Together with @vdakker we were not able to reproduce this in a test case with the same message and repeated testing. But using the debugger we found some moments, where Messages are marked as "The following mandatory field(s) of ContractOfferMessage are not filled or invalid: ids:securityToken, ids:issuerConnector, ids:senderAgent, ids:modelVersion, ids:issued...". 
A screenshot of one such situation (the jsonLD String does not contain a context field):
![Debugger Screenshot of missing context after serialize](https://user-images.githubusercontent.com/83073076/135606428-343f1e1d-da83-48d0-8495-54aee710ad45.png)

We are using infomodel-serializer-4.2.3

**Comment by jschne1der** [comment] 2021-10-06 07:41
My current assumption is, that we have a problem with thread safety, despite the `synchronized` setting. I'm not sure, which part of the method is not thread safe, but I'll try to find other calls to mapper that might be in a conflict.

**Comment by NehaThawani44** [comment] 2021-11-12 09:25
@steffen-biehs @jschne1der @Syd7 On the basis of the information provided in the ticket, we tried to reproduce the issue with more number of threads(4 of each object) as shown in the screenshot but test is still passing. Hence we are unable to reproduce this issue from our end.


![image](https://user-images.githubusercontent.com/8424093/141442836-e390cd87-0e9f-4973-8a2d-a73da75d2166.png)

**Comment by Neo28504** [comment] 2021-11-15 14:22
@steffen-biehs On our side, it seems to happen when using ECS with AWS Fargate, but apparently not when using ECS with EC2 instances. In case you are working on AWS...

**Comment by sebbader** [comment] 2021-11-19 15:54
Hello everyone, it took as some time to understand what was going on. We still cannot reproduce it in our development environments.
Anyway, it looks like a static reference in the serializer code that controls whether or not was the problem. We made it thread-safe and merged a fix into our code base. The `4.2.8` release of the serializer should have this fix.

**Comment by sebbader** [comment] 2021-11-19 15:56
Can anyone from the DSC team test `4.2.8-SNAPSHOT` in the meantime? @ronjaquensel did a first check already and wasn't able to create the error again.

**Comment by steffen-biehs** [comment] 2021-11-22 08:08
Your 4.2.8-SNAPSHOT release fix the bug in my test.

**Comment by sebbader** [comment] 2021-11-24 08:01
Thanks for the feedback. I close the ticket as the problem seems to be solved.

**Closed by sebbader** 2021-11-24 08:01 UTC
